name: Building and pushing a docker image to Amazon ECR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPO_NAME: websocket-server

jobs:
  build-and-push:
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ECR
        run: |
          $( aws ecr get-login-password --no-include-email )
      - name: Build and tag the image
        run: |
          docker build . --build-arg server_port=${{ secrets.AOE_BOT_SERVER_PORT }} -t latest \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:latest
      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:latest
